### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by amorphius** [wunderwaffle/warmagnet#1]
I'm trying to launch your game. After "make migrate" I have this error

```
psycopg2.OperationalError: could not connect to server: Connection refused
    Is the server running on host "localhost" (127.0.0.1) and accepting
    TCP/IP connections on port 5432?

make: *** [migrate] Error 1
```

Did I miss something?

**Comment by sansolovyov** [comment]
Yeah, you have to have pgsql running on localhost having database `warmagnet` (if your setup is different, change `migrations/nomad.ini` and `src/warmagnet/db.clj`).

**Comment by sansolovyov** [comment]
I plan to write a better `README` on how to get all of that up and running, but you'll still need pgsql.
